// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxExpenseTracker.Infrastructure.Data;

#nullable disable

namespace TaxExpenseTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724014937_AddColorToTags")]
    partial class AddColorToTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2c328b0-6d89-4b66-8ef4-fcbe9970a1fd"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "ANZ"
                        },
                        new
                        {
                            Id = new Guid("4c52ddd3-5208-4385-bf85-c1d3e0402ef4"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "CBA"
                        },
                        new
                        {
                            Id = new Guid("69c4e618-d714-4429-b5a2-3a35eb50b343"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Westpac"
                        });
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.LeaveEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LeaveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaveType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LeaveEntries");
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.PublicHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanBeWorkedOn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HolidayDate", "Name")
                        .IsUnique();

                    b.ToTable("PublicHolidays");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165001"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "New Year's Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165002"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "New Year's Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165003"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Australia Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165004"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Australia Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165005"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Good Friday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165006"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Good Friday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165007"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Easter Saturday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165008"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Easter Saturday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165009"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Easter Sunday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165010"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Easter Sunday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165011"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Easter Monday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165012"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Easter Monday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165013"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Anzac Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165014"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Anzac Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165015"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Additional Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165016"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Additional Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165017"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "King's Birthday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165018"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "King's Birthday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165019"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Bank Holiday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165020"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Bank Holiday",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165021"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Labour Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165022"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Labour Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165023"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Christmas Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165024"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Christmas Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165025"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Additional Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165026"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Boxing Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165027"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Boxing Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165028"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2026, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Additional Day",
                            Source = "Seed"
                        },
                        new
                        {
                            Id = new Guid("90e87f20-6fd4-4f68-92a8-61fb6f165029"),
                            CanBeWorkedOn = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HolidayDate = new DateTime(2027, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsImported = false,
                            Name = "Additional Day",
                            Source = "Seed"
                        });
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.TaxExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("SourceId");

                    b.ToTable("TaxExpenses");
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.TaxExpenseTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaxExpenseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("TaxExpenseId", "TagId")
                        .IsUnique();

                    b.ToTable("TaxExpenseTags");
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.Tracker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trackers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e13e64d9-bf27-4232-9af4-b2db537d5faf"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default tracker",
                            IsDeleted = false,
                            Name = "H&R Block",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("03f8e309-dff6-4fd8-b1d8-280e7285687e"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default tracker",
                            IsDeleted = false,
                            Name = "Pluralsight",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8c8208af-c8d8-40f5-99cc-152f6f2f5fb6"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default tracker",
                            IsDeleted = false,
                            Name = "Udemy",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5288117d-0f1f-49ae-9f5f-4f17f8e7d7fb"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default tracker",
                            IsDeleted = false,
                            Name = "JB Hifi",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2eec1c4c-3e14-4375-b6ec-c3e696a84734"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default tracker",
                            IsDeleted = false,
                            Name = "Office Works",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.WorkLocationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkLocation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkLocationEntries", (string)null);
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.TaxExpense", b =>
                {
                    b.HasOne("TaxExpenseTracker.Domain.Entities.Bank", "Bank")
                        .WithMany("Expenses")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxExpenseTracker.Domain.Entities.Tracker", "Source")
                        .WithMany("Expenses")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.TaxExpenseTag", b =>
                {
                    b.HasOne("TaxExpenseTracker.Domain.Entities.Tag", "Tag")
                        .WithMany("TaxExpenseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxExpenseTracker.Domain.Entities.TaxExpense", "TaxExpense")
                        .WithMany("TaxExpenseTags")
                        .HasForeignKey("TaxExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("TaxExpense");
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.Bank", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.Tag", b =>
                {
                    b.Navigation("TaxExpenseTags");
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.TaxExpense", b =>
                {
                    b.Navigation("TaxExpenseTags");
                });

            modelBuilder.Entity("TaxExpenseTracker.Domain.Entities.Tracker", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
