// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxExpenseTracker.Api.Data;

#nullable disable

namespace TaxExpenseTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722011409_AddTaxExpenseTagQueryFilter")]
    partial class AddTaxExpenseTagQueryFilter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TaxExpenseTracker.Api.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TaxExpenseTracker.Api.Models.TaxExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("TaxExpenses");
                });

            modelBuilder.Entity("TaxExpenseTracker.Api.Models.TaxExpenseTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaxExpenseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("TaxExpenseId", "TagId")
                        .IsUnique();

                    b.ToTable("TaxExpenseTags");
                });

            modelBuilder.Entity("TaxExpenseTracker.Api.Models.Tracker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trackers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e13e64d9-bf27-4232-9af4-b2db537d5faf"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default tracker",
                            IsDeleted = false,
                            Name = "H&R Block",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("03f8e309-dff6-4fd8-b1d8-280e7285687e"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default tracker",
                            IsDeleted = false,
                            Name = "Pluralsight",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8c8208af-c8d8-40f5-99cc-152f6f2f5fb6"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default tracker",
                            IsDeleted = false,
                            Name = "Udemy",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5288117d-0f1f-49ae-9f5f-4f17f8e7d7fb"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default tracker",
                            IsDeleted = false,
                            Name = "JB Hifi",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2eec1c4c-3e14-4375-b6ec-c3e696a84734"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default tracker",
                            IsDeleted = false,
                            Name = "Office Works",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TaxExpenseTracker.Api.Models.TaxExpense", b =>
                {
                    b.HasOne("TaxExpenseTracker.Api.Models.Tracker", "Source")
                        .WithMany("Expenses")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("TaxExpenseTracker.Api.Models.TaxExpenseTag", b =>
                {
                    b.HasOne("TaxExpenseTracker.Api.Models.Tag", "Tag")
                        .WithMany("TaxExpenseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxExpenseTracker.Api.Models.TaxExpense", "TaxExpense")
                        .WithMany("TaxExpenseTags")
                        .HasForeignKey("TaxExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("TaxExpense");
                });

            modelBuilder.Entity("TaxExpenseTracker.Api.Models.Tag", b =>
                {
                    b.Navigation("TaxExpenseTags");
                });

            modelBuilder.Entity("TaxExpenseTracker.Api.Models.TaxExpense", b =>
                {
                    b.Navigation("TaxExpenseTags");
                });

            modelBuilder.Entity("TaxExpenseTracker.Api.Models.Tracker", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
